Repository OpenSourceEconomics/econsa, pull requests merged in 2020-07, with the labels that each got.

#51 Update readme
  README.rst
  docs/source/conf.py
Labels: Type: Feature/Enhancement

#54 Add logo in doc homepage.
  docs/source/conf.py
  docs/source/index.rst
Labels: Status: Completed, Type: Feature/Enhancement

#50 Add sampling from copula
  .github/workflows/continuous-integration-workflow.yml
  docs/source/methods/sampling.rst
  econsa/copula.py
  econsa/tests/test_copula.py
Labels: Status: Revision Needed, Type: Feature/Enhancement

#56 Add correlation transforming fuction
  docs/source/methods/sampling.rst
  econsa/correlation.py
  econsa/tests/test_correlation.py
  environment.yml
Labels: Status: Revision Needed, Type: Feature/Enhancement
